services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp_php_web
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - erp-net


  db:
    image: mysql:5.7
    container_name: erp_php_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp_php_mvc
      MYSQL_USER: root
      
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - erp-net

volumes:
  db_data:

networks:
  erp-net:
